### PR TITLE
added js files for each html/handlebars page, added the necessary han…

### PR DESCRIPTION
**Pull request by rtothaoss**
…dlebars files and updated main.handlebars, andnpm installed sweetalert2

### CODE REVIEW

**Comment by rtothaoss** [comment]
Also added very basic markup in check-in file so when you run the server locally you will land on the check-in page

**Comment by rtothaoss** [comment]
Added a doctors and appointments module. 

Don't exactly know what all the columns should be but this should be a good jumping off point.

**Comment by TariqueT** [comment]
**Patient Details Page**  (It's best to put all labels in all caps)
**Patient Details Tab**  

PICTURE OF PATIENT

NAME:
DATE OF BIRTH:
EMERGENCY CONTACT:

ALLERGIES:

**Comment by TariqueT** [comment]
opreportform

**Pull request merged**
